### ISSUE TITLE
SVG thumbnails rendered with white backgrounds instead of transparent

### ISSUE THREAD

**Issue by Slion** [maphew/svg-explorer-extension#108]
I was having an issue where Windows would render SVG thumbnails with a white background which is useless if you have a lot of white icons. Though I recalled that at some point after installing SVG See they were rendered correctly with transparent background. 

It turns out I suspect PowerToys modified the registry to set a different SVG thumbnail provider for some reason.
Here is the relevant registry key: 
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.svg\shellex\{E357FCCD-A995-4576-B01F-234630154E96}`
Which should be set to `{4CA20D9A-98AC-4DD6-9C16-7449F29AC08A}` if you are using SVG See.
In my case it was set to `{36B27788-A8BB-4698-A756-DF9F11F64F84}` by [PowerToys](https://github.com/microsoft/PowerToys/blob/e9ce9ab87a9ca51311a386728e04d653ce77ee9c/src/modules/previewpane/powerpreview/powerpreview.cpp) I believe.

Reinstalling SVG See should fix it.
Just putting this here for the record, feel free to close this issue.

**Comment by SylvainAssemat** [comment]
Hi @slion

Does my problem is related to your fix ? Cause i check the registry and` {4CA20D9A-98AC-4DD6-9C16-7449F29AC08A}` is set.

![SVG](https://user-images.githubusercontent.com/5692760/115106964-36383300-9f68-11eb-8ab9-ac1ac91670a7.png)

**Comment by Slion** [comment]
I'm not sure what we are looking at. Just reinstall SVGSee and see if it helps I guess.
