### ISSUE TITLE
Does not work for me (Win 10)

### ISSUE THREAD

**Issue by Tracer1337** [maphew/svg-explorer-extension#110]
Downloaded ``svg_see_x86.exe``  from the v1.1.0 release, executed it, done the three troubleshooting steps, but the thumbnails are still not there (yes, I have restarted my PC).

![Screenshot](https://user-images.githubusercontent.com/6074468/117180331-5e32ed80-add4-11eb-87b3-1ad69cf5f82a.png)

Can I somehow verify the installation?
Any suggestions?

Thanks in advance 😄

**Comment by RebeccaAtGitHub** [comment]
Hi Tracer1337, 

I had the same issue and tried svg_see_x64.exe afterwards. 
This worked for me.

Maybe that's also a quick fix for you and another hint for troubleshooting for our beloved contributors to this project!

Best regards!

**Comment by Tracer1337** [comment]
@RebeccaAtGitHub Using the x64 installer does also work for me, thanks 👍
