### ISSUE TITLE
Background No Longer Transparent but Black

### ISSUE THREAD

**Issue by JLChamberlain** [maphew/svg-explorer-extension#17]
No longer is the transparency of the SVG in the preview! The transparency is replaced with a black background which makes any black SVG's fully unviewable in explorer. The SVG needs to display like how a png would in explorer (keep the transparent part of the image transparent)

**Comment by azboul** [comment]
Same here. I've installed _dssee_setup_x64_v011_signed.exe_ on my Windows 10 laptop.

**Comment by MiroslavVanicky** [comment]
Same for me.

**Comment by maphew** [comment]
Closing, as is this is fixed in #32. Please note this means that the _code_ is fixed. It will still be an indefinite time until the installer is updated to include the fix (because I haven't learned how yet).
