### ISSUE TITLE
compiler error: no member named 'toWinHBITMAP' in 'QPixmap'

### ISSUE THREAD

**Issue by maphew** [maphew/svg-explorer-extension#19]
> ThumbnailProvider.cpp:141: error: no member named 'toWinHBITMAP' in 'QPixmap'

`toWinHBITMAP` doesn't have a clear drop-in replacement, but there is https://stackoverflow.com/a/50236645/14420, "It was moved into the QtWin namespace."

**Comment by maphew** [comment]
_baby steps._

**Solved**: including the new QtWin module (424cff6). This means adding an `#include <QtWin>` to the .cpp file and adding `QT +=winextras` to the .pro project file. Unless **both** of these are in place inlcude yields a "file not found" error.

Now trying to figure out how to convert `*phbmp = QPixmap::fromImage(*device).toWinHBITMAP(QPixmap::Alpha);` into something that works.

    // Old syntax:
    HBITMAP QPixmap::toWinHBITMAP(HBitmapFormat format = NoAlpha) const
    // New syntax:
    HBITMAP QtWin::toHBITMAP(const QPixmap &p, QtWin::HBitmapFormat format = HBitmapNoAlpha)

This isn't it:

    *phbmp = QtWin::fromImage(*device).toHBITMAP(QPixmap::Alpha);

Yields:

    ...\ThumbnailProvider.cpp:149: error: C2039: 'fromImage': is not a member of 'QtWin'

**Comment by maphew** [comment]
With edb20b6bc50ea59f2888889aff82b6981985ba21 there are no more errors related to bitmap conversion, so closing. However just because the compiler is happy doesn't mean the code is doing the right thing! ;-)

**Comment by GitMensch** [comment]
... actually this breaks the compilation with old QT versions, I'll PR a check with `#if QT_VERSION >= 0x050200` to use either the old or the new code (and the include).

**Comment by maphew** [comment]
that would be great, thank you
