### ISSUE TITLE
Figure out how to test and install build results

### ISSUE THREAD

**Issue by maphew** [maphew/svg-explorer-extension#22]
_Now that the build environment appears to be resolved (#18). Next up is to figure out how to test and install the results._ 

For testing it might be enough to grab the .dll's in https://github.com/maphew/svg-explorer-extension/tree/master/build-SVGThumbnailExtension-Desktop_Qt_5_12_3_MSVC2017_64bit-Debug/debug and replace the same wherever the same exist on a system that has a [previous release](https://github.com/maphew/svg-explorer-extension/releases) installed.

I've no idea yet how to create an installer.

**Comment by maphew** [comment]
On the testing front: 

I added 2 svg files to `.\test\art`. One is a text svg file the other gzip compressed (.svgz). On my machine only .svg shows a preview:

![image](https://user-images.githubusercontent.com/486200/64657360-de2e6780-d3e7-11e9-809e-19a39f70f6f5.png)

No preview for .svgz is fine, because that was only added a while ago and isn't in the latest release. However now I have a quandary: how do I know that the working preview is from this extension and not from something else? Note that it has a Chrome icon overlay. 

Second, if I'm to test new versions of the .dll, like the one I created yesterday, how do I know in Explorer that I'm seeing the results of _this_ version and not the _old_ version? And how do I accurately test without SVG Extension at all? (can I trust that using Add/Remove Programs is enough?)

I don't know how to answer these questions.

**Comment by drewnoakes** [comment]
> how do I know that the working preview is from this extension and not from something else?
>
> how do I know in Explorer that I'm seeing the results of this version and not the old version?

Can you make your development builds write something into the preview image? Perhaps the build time/hash.

**Comment by maphew** [comment]
Good idea @drewnoakes. I've no idea how to accomplish that though. On the other hand, 2 weeks ago I had no idea how to build binaries at all so maybe I can figure it out ;-)

**Comment by maphew** [comment]
Closing. Now that an automatic route to installer is working (#27) testing is a matter of installing new version.
