### ISSUE TITLE
create installer

### ISSUE THREAD

**Issue by GitMensch** [maphew/svg-explorer-extension#27]
It would be best if we can get the CI build to create it (would also fix #22).

To create the installer the following things would be needed:

# Option 1
Get rid of the install shield scripts and start a new installer based on WiX or Inno or NSIS. Seems to be more work than option 2 but also seems to be better prepared for the future.

# Option 2
Stay using proprietary InstallShield (either someone has a version and can do the steps or we'd be stuck to VS2015 which gives the option to use [Install Shield LE](https://info.flexerasoftware.com/IS-EVAL-InstallShield-Limited-Edition-Visual-Studio))

- [x] update the installer scripts [SVGThumbnailExtension.iss][1] and [SVGThumbnailExtension_x64.iss][2]
   - [ ] update meta data (the URLs are all broken and the names can use an update, no need for a sub-folder under programfiles above the extension folder)
   - [x] ideally include the version number from somewhere else (check if this is possible)
   - [ ] use paths of the "new" build system

[1]:https://github.com/maphew/svg-explorer-extension/blob/master/SVGThumbnailExtension/SVGThumbnailExtension.iss
[2]:https://github.com/maphew/svg-explorer-extension/blob/master/SVGThumbnailExtension/SVGThumbnailExtension_x64.iss

Any opinions?

_Optional for every case: check if someone sponsors a certificate to be used for the binaries and the installer._

**Comment by maphew** [comment]
I'm in agreement with the principle of using CI for builds. See #28 for the meagre progress on so far. As for option opnions, I tend to favour right over expedient. That said I give greatest weight to whomever is in the middle actually doing the work over my preferences.

**Comment by GitMensch** [comment]
I think I'll give this a try in some weeks (trying wix-only, if it doesn't work out then wix, wrapping inno-setup). You may ping me about this if you miss a response.

**Comment by maphew** [comment]
Great, thanks Simon. I really appreciate your interest and contributions. FYI, a colleague pointed me to https://build-system.fman.io/ recently. It promises to simplify many things; no idea about the follow through.

**Comment by maphew** [comment]
I managed to get Appveyor build working! See #28. Hopefully this can be leveraged for your work @GitMensch .

**Comment by maphew** [comment]
suggestion from @voodoo66 https://github.com/maphew/svg-explorer-extension/pull/32#issuecomment-568574714
> If the AppVeyor docs are correct than there should be an InnoSetup installation under:
> `C:\Program Files (x86)\Inno Setup 5`
> look for InnoSetup at: AppVeyor WinImage
> 
> You only have to to call:
> `C:\Program Files (x86)\Inno Setup 5\ISCC.exe <.iss-file-path>`
> 
> It's also possible to pass values to the iss script, e.g. the Qt path:
> `C:\Program Files (x86)\Inno Setup 5\ISCC.exe <.iss-file-path> /dQTDIR=%QTDIR%`
> and to use them in the iss script, like this:
> `Source: "{#QTDIR}\Qt5Core.dll"; DestDir: "{app}";`

**Comment by maphew** [comment]
I added `pushd "C:\projects\svg-explorer-extension\SVGThumbnailExtension" && 
"C:\Program Files (x86)\Inno Setup 5\ISCC.exe" SVGThumbnailExtension_x64.iss` to [build settings](https://ci.appveyor.com/project/maphew/svg-explorer-extension/settings)\* 

It works until encountering a missing file referenced in .iss, but that's okay, this is progress!
https://ci.appveyor.com/project/maphew/svg-explorer-extension#L58

>Error on line 24 in C:\projects\svg-explorer-extension\SVGThumbnailExtension\SVGThumbnailExtension_x64.iss: Could not read "C:\projects\svg-explorer-extension\SVGThumbnailExtension\license.txt".


_\* nb: there must be a way to have this script in source code control also._

**Comment by maphew** [comment]
Thanks to @voodoo66 we have a working installer builds in Appveyor:

> Successful compile (4.219 sec). Resulting Setup program filename is:
> C:\projects\svg-explorer-extension\installer\dssee_setup_i386.exe

Next up is to enable pushing to Github Releases

**Comment by maphew** [comment]
Appveyor is now automatically both building and pushing binaries to GitHub releases. There's still some fine tuning to do so that only certain tags are promoted to releases instead of every single commit, but the hard part is done. **Thank you @voodoo66!**
