### ISSUE TITLE
Document appveyor build settings

### ISSUE THREAD

**Issue by maphew** [maphew/svg-explorer-extension#37]
The way I've set this up, the Appveyor continuous integration system settings are not stored in the source code repo. The [docs state](https://www.appveyor.com/docs/build-configuration/#configuring-build) that one can use _either_ the web UI or an `appveyor.yml` file in the repo. Also some UI settings are just not available in the .yml file. For the present at least we'll stick with the UI approach.

So, I need to document how things have been set up to get to where we are now, so that someone else can do the same without having to spend as much time with trial and error as I have.

**Comment by GitMensch** [comment]
I suggest to instead use the existing UI-created definition and include it in the repository instead: Settings->Export YAML; Download; then commit to the repo. Adjusting the file should then also allow to only push to GH if its tagged (or pushed to a release branch).

**Comment by GitMensch** [comment]
... this way you also could integrate the build-appveyor.cmd easily into the yaml.

**Comment by maphew** [comment]
Done. I didn't know about the export route. That's much faster (for me) than trying to write correct yaml by hand. (It took me hours to get it right for Travis-ci on a different project.)

Appveyor is now set to only deploy to Github from *release* branch (which isn't created yet).

**Comment by GitMensch** [comment]
Both sounds good.
Note: I suggest to replace the version number to 0.9.{build} (with or without resetting the build number) to save "1.0" for the upcoming release.
