### ISSUE TITLE
wrong qt include paths?

### ISSUE THREAD

**Issue by GitMensch** [maphew/svg-explorer-extension#39]
I try to compile this extension with an old QT version and it seems some paths are not setup correct (some of the includes use sub-paths, others not).

While I'm still in the process to check if this actually works out or not, these are the current changes needed - are those fine to be done in general or should there be an ifdef guard around this?

```diff
-#include <QSvgRenderer>
-#include <QString>
-#include <QDateTime>
+#include <QtSvg/QSvgRenderer>   // guess that's fine as we use it in common.h
+#include <QtCore/QString>  // other files from QtCore are used in different places
+#include <QtCore/QDateTime>
```

When this is clear I'll finish my changes and PR them.

**Comment by GitMensch** [comment]
Just checked the CI output which shows the includes `I..\..\..\Qt\5.13.2\msvc2017_64\include -I..\..\..\Qt\5.13.2\msvc2017_64\include\QtSvg -I..\..\..\Qt\5.13.2\msvc2017_64\include\QtWidgets -I..\..\..\Qt\5.13.2\msvc2017_64\include\QtWinExtras -I..\..\..\Qt\5.13.2\msvc2017_64\include\QtGui -I..\..\..\Qt\5.13.2\msvc2017_64\include\QtANGLE -I..\..\..\Qt\5.13.2\msvc2017_64\include\QtCore -Irelease -I/include -I..\..\..\Qt\5.13.2\msvc2017_64\mkspecs\win32-msvc` - so I *think* the options above would be "correct" (would have no result on the current build environments including CI as currently both the "parent" qt-include and the sub-include-paths for QtSvg and QtCore, ... are specified).

**Comment by tibold** [comment]
Are you upgrading to the latest version of Qt? :)

**Comment by GitMensch** [comment]
No, I'm actually downgrading to qt4.

**Comment by tibold** [comment]
Oh? Any particular reason you need qt4? Just curios

**Comment by GitMensch** [comment]
I don't need QT4, just don't want to download GB without any need (especially if I seem to only get it via "online installer" [I just need the headers and libraries and did not found a direct way to download a newer version, the latest offline installer I've found was a mirror from nokia's old dev site - and this offline installer is also what was used years ago to get my qt setup]
