### ISSUE TITLE
switch `maphew` refs to `tibold`

### ISSUE THREAD

**Issue by maphew** [maphew/svg-explorer-extension#42]
Scattered throughout there are paths and other references to `maphew/svg-explorer-extension` that will need to be converted to `tibold/svg-explorer-extension` once #7 is complete. This is a collector issue for those references (e.g. treat opening comment as a wiki)

- [x] `Readme.md` - installer locations; CI build status
- [x] `appveyor.yml` - auth token
- [x] `.all-contributorsrc`
- [x] `SVGThumbnailExtension\SVGThumbnailExtension.pro.user`
- [x] `SVGThumbnailExtension\ThumbnailProvider.cpp`

**Comment by GitMensch** [comment]
Another thing for the README: actually update its content (possibly adjusting the history session, adding maphew to the contributors, ...) :-)

**Comment by tibold** [comment]
Is there any other place that still needs changing?

**Comment by maphew** [comment]
The Appveyor etc. CI references were the only remaining ones I'm aware of, and that's done now, so closing!
