### ISSUE TITLE
Trend Micro reports Appveyor installer as "potential ransomware"

### ISSUE THREAD

**Issue by maphew** [maphew/svg-explorer-extension#43]
Trend Micro reports the appveyor install .exe's are "potential ransomware".
After pressing [Allow Once] the programs runs as normal (notwithstanding error #36).

Microsoft Windows 10 Enterprise  
Version	10.0.18362 Build 18362  
Trend Micro 11.000.1006

![image](https://user-images.githubusercontent.com/486200/71530885-09f33180-28a1-11ea-8f63-a3da4ef00552.png)

![image](https://user-images.githubusercontent.com/486200/71530996-956cc280-28a1-11ea-8891-5c1b90243c64.png)

**Comment by tibold** [comment]
I had similar reports with the original release. Back then I have submitted the signed installer (before the signature expired) to the companies for review, but never heard back anything.
Not sure what they don't like in the code.

**Comment by maphew** [comment]
I'll try asking through our corporate subscription. That might be high enough on the food chain that they will be compelled to answer.

**Comment by tibold** [comment]
Thanks @maphew ,

The reason in the first dialog suggest that it would mark every newly encountered program as a potential ransomware. :) I mean I do understand and like zero trust computing. XD

Maybe the code signing will help with this as well.

**Comment by GitMensch** [comment]
At least the 64bit version is fine [according to VirusTotal](https://www.virustotal.com/gui/file/41ffc71789830720d465576dfdc8ec235f9464eec5c96d72f1a8d215676125a1/detection).

**Comment by maphew** [comment]
I haven't gotten this warning on any installer built in the last 12 days. In other words:

...this is the last one that triggers the warning (still does today, so it's not a change on Trend Micro's side):
https://ci.appveyor.com/project/maphew/svg-explorer-extension/builds/29780651/artifacts
...and this is the first one that doesn't:
https://ci.appveyor.com/project/tibold/svg-explorer-extension/builds/29898389/artifacts
...and all newer ones seem to be fine, so I'm closing the issue. (I didn't test every artifact.)

So everything from commit b5012707e131afd6e4e96d67f5a6c3ec0ba00eea forward is clean as far as Trend Micro is concerned.
