### ISSUE TITLE
Shorter project name?

### ISSUE THREAD

**Issue by maphew** [maphew/svg-explorer-extension#49]
_'SVG Explorer Extension'_ is rather long to say and type. What about _see-svg_ or _svg-see_ instead? 

The 2nd embeds a nice recursion. ;-)

**Comment by drewnoakes** [comment]
svg-see is nice. Do you have analytics that shows what people search for to find this extension? I would guess a lot of people are looking for "svg thumbnail", but cold hard data would be interesting.

**Comment by tibold** [comment]
I was also playing with the thought of changing the name.

Please also consider that I am planning to extend the current functionality with the following:
* [Property handlers](https://docs.microsoft.com/en-us/windows/win32/search/-search-3x-wds-extidx-propertyhandlers?redirectedfrom=MSDN)
* Simple viewer with rendering capabilities, eg. render single file or folder into png/jpeg etc.
* Maybe simple transformations like replace color, etc.

This are common tasks I myself have to do over and over. So far I just wrote a simple Python script using PIL.

--- 

Any ideas how to get data on how people find the site? GitHub itself gives me some basic stats but not a lot on search terms for instance.

**Comment by GitMensch** [comment]
With the additional functions I'd vote for keeping the long name.

**Comment by maphew** [comment]
I'd use a short name even with the added features. The ones mentioned all still revolve around seeing. (Properties, which sounds excellent, stretches it a bit, but not too much.)  

I've wondered how people find the project too. I know there's a Super User page referencing it. The favourite tagging sometimes comes in waves, a handful of people in a day or two. I presume these ones are word of mouth (well, keyboard).

It's surfaced on twitter a few times, https://twitter.com/search?q=svg%20explorer%20extension&src=typed_query. Hmmm, a suprising number of new ones still reference google code and codeplex sites.

**Comment by tibold** [comment]
FYI, I am playing the `SvgSee` name in #36.

**Comment by GitMensch** [comment]
Is this solved as "stays as is"?

**Comment by tibold** [comment]
No, I started renaming the project to `SvgSee`.
There are a few more things left to do though.
