### ISSUE TITLE
provide pgp signatures for releases

### ISSUE THREAD

**Issue by GitMensch** [maphew/svg-explorer-extension#50]
It is good to explicit list the hashes for the installers as it is done now (= ensuring that the binary was not tinkered with or got broken afterwards).
It would be even better to provide pgp signed source snapshots and binaries as this *additional* ensures that both were actually released by @tibold (as soon/long as his public key is known).

**Comment by tibold** [comment]
Good idea, especially since I don't have other code signatures.
I'll have to read up on it. I have only used pgp for e-mail encryption before.

**Comment by GitMensch** [comment]
https://www.dewinter.com/gnupg_howto/english/GPGMiniHowto-5.html for the overview, for possible copy & past `gpg --detach-sign --armor -o source.tar.gz.asc source.tar.gz`, for verification https://www.cyberciti.biz/faq/pgp-tarball-file-signature-keys-verification/ has a nice formatted howto.

**Comment by tibold** [comment]
Thanks, I'll take a look!

**Comment by tibold** [comment]
I've create a gpg key and submitted it to `keyserver.ubuntu.com`;
```
6D754F00A54D4C7CEA068C4ACCCEF39672AD372A
```

I'll have the next set of installers signed with this key.

**Comment by tibold** [comment]
Included the installer signing in the build script in #70
