### ISSUE TITLE
[Feature Request] Revert to default SVG Icon for Invalid SVG

### ISSUE THREAD

**Issue by raymondlaw** [maphew/svg-explorer-extension#58]
Currently if there's an invalid SVG icon, the preview will display a transparent image with some text (It's a bit hard to read, but I think it says "Invalid SVG File" in red)

![ex](https://user-images.githubusercontent.com/2231426/71771778-c76bcd80-2f0e-11ea-9e80-7a8687b10b5a.PNG)

Windows displays invalid images (jpg, png, webp) using the default file icon, and I was thinking using the default svg icon of (whatever viewer they use IE, AI, ImageGlass, ... ) would be more consistent.

Is the current behavior intended?

**Comment by tibold** [comment]
Originally this was a debugging feature, but was left there for the release.

I do like to be consistent with the behavior though.

---

Does `webp` files not have thumbnails or is that just an example of an invalid file? :)

**Comment by raymondlaw** [comment]
That's just an example of an invalid file.  Right after I posted the image, I realized I should've named them `invalid.svg` and `invalid.webp`

**Comment by tibold** [comment]
Fixed in #61
