### ISSUE TITLE
Please add to readme: how-to-use instructions/results expected after installation

### ISSUE THREAD

**Issue by JoanEliot** [maphew/svg-explorer-extension#62]
Such as: "This is an Explorer extension so there's nothing further to do and no application to run. After installation just navigate in File Explorer to a folder that contains SVGs, and you'll see the contents of those files as their thumbnails, rather than generic icons. If you have the Preview pane open, you'll see a bigger thumbnail there." Needs work on the wording but I hope that gives you the gist of my request. A screenshot would be helpful, perhaps. 

Just a little info of this sort, as obvious as it may seem, would be helpful in general for some I think, and would definitely make it clear that when nothing happens after installation something is wrong. That's my situation: I'm pretty sure but not certain, since nothing is said one way or the other, that after you install (the correct version) and then run the little set of system commands, it's supposed to be that nothing further is required: when you browse/Explore you see your SVGs. But since that didn't work for me I'm left wondering: am I missing something, or did the install procedure just not work for me? Am I supposed to manually register the DLL? I will eventually reboot but is that likely to work if the iconcache clearout didn't?

Thank you.

**Comment by tibold** [comment]
You are correct. After the installation the thumbnails and previews should _just_ work. Sometimes it is necessary to force clean the thumbnail cache. There are instructions on the readme how to.

You can also use the Disk Cleanup tool:
![image](https://user-images.githubusercontent.com/1974659/72021195-c5d33a00-326d-11ea-9413-6a8c6327ce10.png)

You are **not** supposed to manually register DLLs.

--- 

If the clearing the thumbnail cache and rebooting doesn't help we can investigate and find a solution of course. Let me know if this helps.

I'll leave this task open to update the readme with such information.

**Comment by maphew** [comment]
The readme improvement recommendation is good one.

Also ensure that "Always show icons, never thumbnails" option under _"Explorer: View >> Options"_ is NOT checked.

![image](https://user-images.githubusercontent.com/486200/72026143-550d2d00-322f-11ea-935b-9e633d7fbd52.png)

**Comment by mybesttools** [comment]
Tried the install and all instructions. Not working for me. I just get errors about Qt not being available.
![image](https://user-images.githubusercontent.com/2362821/73604959-59abd380-4598-11ea-9b4c-a5853a8d142d.png)

**Comment by tibold** [comment]
@mybesttools, this has been fixed in #64

**Comment by tibold** [comment]
Fixed in 1d257e348a45cdd68aedb48a0a055e77b4676735 and 71e45904c346ced278c5f2a4b8b9201fd7bdc191
