### ISSUE TITLE
"This application failed to start becuse no Qt platform plugin could be initialized"

### ISSUE THREAD

**Issue by FlorianReimold** [maphew/svg-explorer-extension#64]
After installing the x64 version on Windows 10 1809 x64, I only get the following error:

"This application failed to start becuse no Qt platform plugin could be initialized. Reinstallling the application may fix this problem."

![error](https://user-images.githubusercontent.com/11774314/72527157-675b1c80-3868-11ea-8ec2-0ffef408559c.png)

I myself develop Software with Qt 5, so my PATH is full of directories containing Qt5 DLLs in various versions. Could that be an issue, that SvgExplorerExtension picks the wrong Qt5Core dll?

**Comment by FlorianReimold** [comment]
OK, got it, I went through the closed issues and found that this has been solved in #36, but the fix hasn't been released as binary, yet.

**Comment by tibold** [comment]
Hey!

Yep, I’ll release an update this Sunday. :)

**Comment by jartaud** [comment]
@FlorianReimold You're right. I download the version 1.0.19 from here: https://ci.appveyor.com/project/tibold/svg-explorer-extension/builds/29933374/artifacts and it works.
