### ISSUE TITLE
This application failed to start because no Qt platform plugin could be initialized!

### ISSUE THREAD

**Issue by kn9** [maphew/svg-explorer-extension#66]
Hi There,

I can't install SVG Explorer Extension. keep getting the error message 

The application failed to start because no Qt platform plugin could be initialized

![image](https://user-images.githubusercontent.com/5074663/73410018-e3d60c80-42f8-11ea-94db-3beb2f7906fb.png)

**Comment by maphew** [comment]
This is believed fixed in #36.  Try a recent Automatic Build - https://ci.appveyor.com/project/tibold/svg-explorer-extension/build/artifacts - and re-open if you still get same message
