### ISSUE TITLE
Project Maintainer(s) wanted

### ISSUE THREAD

**Issue by maphew** [maphew/svg-explorer-extension#7]
I imported the svg-explorer-extension from CodePlex posted here to GitHub because I use the extension and I didn't want to lose access to it when CodePlex shut down in 2017. 

I'm primarily a python guy and am ill equipped to maintaining this project. So if you know C++ and have some time to spare, please feel free to take over! In the meantime I'm happy to merge pull requests for those who care to offer drive-by fixin's but can't vet them for quality or completeness. ;-)

cheers, Matt

- [x] Transfer to Tibold _(started)_
- [ ] #42 update paths

**Comment by MichielBlotwijk** [comment]
I'm neither a python nor a C++ guy, so I can't help you here. I just wanted to express my gratitude for the work you've already done. It works flawless on my Win10-64 machines. Thanks!

**Comment by maphew** [comment]
Good news on the maintainer front: Thanks to efforts by David P. I've made contact with original project author @tibold! He has spare time now and is interested in picking up SVG Extension again. I'll be reading up on how to transfer the project to him and keep all the issues etc. intact.

**Comment by tibold** [comment]
Hey @maphew,
Thanks for keeping the project alive. :) For while I was under the impression that Windows 10 was finally able to render SVG thumbnail on it's own. Recently I started using logos again and was really surprised when the IE icons showed up. :D 

Now I just need to hunt down where did I get the free open source code signing certificate.

BTW the transfer option is under Settings/Danger Zone. ^_^

**Comment by maphew** [comment]
Ok, transfer initiated, and I've done all the work I can think of to make the process easier; mainly putting the Appveyor settings into the code repo. I'll stop changing things now! future changes will be with PR. There'll be some post move clean up (#42).

**Comment by tibold** [comment]
Thanks fore reaching out to me. It just happened that I left the corporate world behind me a few months ago and now working in a small growing business that gives me free time to work on side projects.
I have accepted the transfer.
Next order of business is to get a VM to develop in and code signing certificate. :)

**Comment by GitMensch** [comment]
@tibold I like the new README. Note: The contributors part seems a bit strange (both you and maphew are missing and the counter _may_ be wrong). _Possibly_ the qt (as "Qt's contributors") and Jeremy entries under thanks can be included there instead of their own paragraph, too.

**Comment by tibold** [comment]
Thanks @GitMensch ,
and thanks for @maphew for writing the history.

I'll read up the all-contributors spec how it works and update it, I saw there is a bot and I got that installed to this repo now.

FYI the project actually started in 2012 on google code: https://code.google.com/archive/p/svg-explorer-extension/ but for reasons I don't remember anymore, I have migrated the project to CodePlex. Maybe there were shutting down google code already.

**Comment by maphew** [comment]
I adjusted Readme in _develop_ branch as per above. Now let's test all-cotnributors:

@all-contributors please add @tibold for ideas and code, @maphew for maintenance, @GitMensch for docs and code

**Comment by GitMensch** [comment]
Looks like [the bot only takes on contributor per line](https://allcontributors.org/docs/en/bot/usage) and ignores everything "unknown" (like additional entries = the user names). The tibold entry is correct nonetheless :-) Just to check who is allowed to do so:

@all-contributors please add @maphew for maintenance
@all-contributors please add @GitMensch for docs and code

**Comment by GitMensch** [comment]
@all-contributors please add @maphew for maintenance

**Comment by GitMensch** [comment]
@all-contributors please add @GitMensch for docs and code

**Comment by GitMensch** [comment]
Looks like it parses an issue post and handles only one addition/change per issue.
I just was curious; sorry for polluting this issue.

**Comment by maphew** [comment]
I was curious too, so if it wasn't you it would have been me being noisy.
