### ISSUE TITLE
DllHost: no Qt platform plugin could be initialized.

### ISSUE THREAD

**Issue by GiovanH** [maphew/svg-explorer-extension#72]
After having this program installed and working with no problems, I uninstalled it for unrelated reasons. When I reinstalled it, though, it doesn't work.

I get this error message every time it tries to render an SVG thumbnail in the background:

```
---------------------------
DllHost
---------------------------
This application failed to start because no Qt platform plugin could be initialized.
Reinstalling the application may fix this problem.

---------------------------
OK   
---------------------------
```

SVG files do not render.

Deleting the program and reinstalling it does not resolve the issue.

**Comment by GiovanH** [comment]
With more experimentation, I determined that the old 0.1.1 release works correctly, but the new 1.0.0 release does not work at all, as described.

**Comment by Tymski** [comment]
![image](https://user-images.githubusercontent.com/8183632/74108062-7c308480-4b76-11ea-9b1c-3348374ce25f.png)

**Comment by Daan4** [comment]
I get the same popup as Tymski, followed by this one

![image](https://user-images.githubusercontent.com/1859384/74222818-9755de00-4cb5-11ea-9a04-526e1e4b7217.png)

The windows defender smartscreen filter also complains when running the installer.

Version 0.1.1 still works though.

**Comment by johanponken** [comment]
I get these two popups, but at installation.
[v1.0.0 64b on 64b Win10 1603 - yes, I know it's old but I'm unable to upgrade]
So I chose to not install (-->"rolling back changes").
I wonder what happened for @GiovanH at install.

**Comment by Tymski** [comment]
Just use the first release. It appears to be working.
https://github.com/tibold/svg-explorer-extension/releases/tag/v0.1.1

**Comment by maphew** [comment]
Try a recent automatic build: https://github.com/tibold/svg-explorer-extension#automatic-builds

**Comment by andreszs** [comment]
![image](https://user-images.githubusercontent.com/10298071/76702002-19fefe00-66a5-11ea-8789-2cf8edecd8de.png)

**1.0.0** Setup

**Comment by bigbird1985** [comment]
https://ci.appveyor.com/project/tibold/svg-explorer-extension/builds/30968882/artifacts  Try this build, work perfect.

**Comment by tibold** [comment]
A new release was posted today should solve this.
Feel free to re-open if the issue persists.
