### ISSUE TITLE
When will the signed version be available?

### ISSUE THREAD

**Issue by nasserakhter** [maphew/svg-explorer-extension#73]

**Comment by andreszs** [comment]
What's the difference anyway? The so called "_signed_" x64 installer does not even provide a verified **publisher** :roll_eyes: 

![image](https://user-images.githubusercontent.com/10298071/76702075-b6290500-66a5-11ea-8699-05de3d2b1d9f.png)

**Comment by tibold** [comment]
Those old binaries are there for historical reasons.
Their signature is not valid anymore.

Back in the day there were options for a free open source code signing certificate.
Once I can find an affordable solution today, I'll have the new installers signed. In the mean time only gpg signatures will be provided.
