### ISSUE TITLE
The installer reboots the machine without notice

### ISSUE THREAD

**Issue by abdelhakoussaid** [maphew/svg-explorer-extension#79]
The installer did restart my machine without any notification, I did install the lastest version. I'm on Windows 10 Home X64.

**Comment by maphew** [comment]
Can you clarify precisely which latest version was used, as in what url was used or the navigation path to get to it?

**Comment by abdelhakoussaid** [comment]
I used the version 1.0.0 and I have downloaded svg_explorer_extension_x64.exe from the releases section. For the installation I have kept everything as default (I hit next until finished).

**Comment by maphew** [comment]
@tibold even though signed installers can't be created yet, perhaps a dot release from the [automatic builds ](https://github.com/tibold/svg-explorer-extension#automatic-builds) should be tagged as a release to stop people from experiencing this?

**Comment by tibold** [comment]
This has been fixed in 86a87587670da6d00ec9857b11831bb030faf63a

Apparently I forgot to upload a new release.
@maphew , yes I'll get a new build uploaded to the releases.
