### ISSUE TITLE
Windows 10 Explorer doesn't autorefresh after creating/deleting a file/folder

### ISSUE THREAD

**Issue by thiemeljiri** [maphew/svg-explorer-extension#8]
Hi,
I've just installed this app on my Windows 10 64-bit and I'm having the following issue. My Explorer doesn't autorefresh after creating/deleting a file/folder. I've tried several things. Uninstalling the app and event this https://answers.microsoft.com/en-us/windows/forum/windows_10-files/win-10-64-bit-file-explorer-auto-refresh/703492e6-dffb-4344-9699-7e41b2c4ddee?auth=1 But nothing helped. Is there a way how to remove the app completely and revert any system change it did? Uninstalling it via Windows "Add or remove programs" just wasn't enough. It seems that it still left some of it's folder/files.

Thanks.
Jiri

**Comment by maphew** [comment]
Perhaps try **Revo Uninstaller** in it's "monitor" mode. This would require installing svg-explorer-extension again so it can watch what it touches and then later remove it. Oh, I just read monitor mode is a Pro feature. There are other uninstaller apps too. I've usd **Bulk Crap Uninstaller** before to good effect.

* https://www.revouninstaller.com/
* https://www.bcuninstaller.com/

**Comment by glachancecmaisonneuve** [comment]
```reg
Windows Registry Editor Version 5.00

[-HKEY_CLASSES_ROOT\CLSID\{4CA20D9A-98AC-4DD6-9C16-7449F29AC08A}]
[-HKEY_CLASSES_ROOT\.SVG\shellex\{E357FCCD-A995-4576-B01F-234630154E96}]
```

**Comment by thiemeljiri** [comment]
Hi,
thank you for your replies. It may be very useful when someone has similar problem as me.

In the end, the problem wasn't probably the installation of this extension, but probably some bug on Mixrosoft's side. As I updated my Windows 10 copy before actually proceding to the steps above and it started working again.

Thank you wery much. Your app is really useful! Pity Windows can't handle SVG by default :/ Is there any MS thread for it where I could vote for that feature?

Cheers,
Jiri

**Comment by tibold** [comment]
Hey @thiemeljiri ,
Try the `Feedback Hub` app. I am surprised myself too that this is not a built-in feature. :)

I am closing this issue since the problem seems resolved and old.
