### ISSUE TITLE
[Feature Requeest] White SVG not visible, add chessboard on the background

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [maphew/svg-explorer-extension#81]
just add a checkerboard texture to the transparent areas of svg, then people will have an understanding that where chess, and all icons will be visible, including white ones, and even translucent

![image](https://user-images.githubusercontent.com/60403187/81126358-b7f3a400-8f43-11ea-96be-bb009f8d4a7b.png)

![image](https://user-images.githubusercontent.com/60403187/81126353-b4601d00-8f43-11ea-9d38-acc55bfdfc48.png)

**Comment by kbravh** [comment]
This issue has been brought up here: https://github.com/tibold/svg-explorer-extension/issues/15

**Comment by maphew** [comment]
closing in favour of the older issue
