### ISSUE TITLE
Machine restart with any warning / confirmation

### ISSUE THREAD

**Issue by zehawki** [maphew/svg-explorer-extension#82]
Upon installation, without any warning or permission, this program just sends a forced reboot. That's terrible practice, or?

(What a mess to happen in the middle of work, with so many programs open at various stages. I was saved by Windows asking for confirmation since it was not able to force close some programs and there I managed to cancel the restart without much damage.)

Unfortunately ended up uninstalling this right after.

**Comment by maphew** [comment]
Duplicate of #79, and yes auto restarts is not good at all.
