### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by rightmark** [maphew/svg-explorer-extension#83]
finally I got a message from regsvr32:
> This application failed to start because no Qt plarform plugin could be initialized. Reinstalling the application may fix this problem.

app reinstall does not help. system restart does not help as well.
Win10, 
currently installed Qt 5.13,
SVG extension v0.1.1 was installed and uninstalled manually before this new install.

**Comment by maphew** [comment]
Try one of the  [automatic builds](https://github.com/tibold/svg-explorer-extension#automatic-builds). Also see https://github.com/tibold/svg-explorer-extension/issues/72#issuecomment-610848801 that references a particular build several have confirmed worked for them. 

If that doesn't work feel free to re-open this issue and add whatever more detail might help troubleshoot.
