### ISSUE TITLE
SVGZ is not supported

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [maphew/svg-explorer-extension#9]
(Nothing else to say here)

**Comment by Daniel-Beardsmore** [comment]
GitHub seems content to wait forever for my fork. I tried giving it a spoon instead, but it seems there is no spoon.

In Main.cpp, take this line:

{HKEY_CLASSES_ROOT, L".SVG\\shellex\\{E357FCCD-A995-4576-B01F-234630154E96}", NULL, REG_SZ, (DWORD_PTR)szCLSID_SampleThumbnailProvider}

Duplicate that and change .SVG to .SVGZ.

I just tested a manual Registry edit and SVGZ is read correctly.

**Comment by maphew** [comment]
Thanks! I didn't notice the associated PR or I would have merged right away.
