### ISSUE TITLE
Are Install instructions up-to-date?

### ISSUE THREAD

**Issue by eLIANT-TechnologyServices** [maphew/svg-explorer-extension#93]
I'm new to Github so maybe the answer to my questions is painfully obvious, but the installation steps in the README.MD file don't match what is available on the Github page for this product.

They say, "download and run appropriate binary for your system," but Github shows no reference to a binary - only a ZIP file, and it doesn't appear to contain a binary file.  And there's only one of those Zip files;  there's not a 32-bit and a 64-bit zip to download.

So, what exactly should I be downloading?  Is there an .EXE file to run, or what?

**Comment by tibold** [comment]
Hey,

The binary downloads are on the release page.
https://github.com/tibold/svg-explorer-extension/releases

Tibold
